### ISSUE TITLE
How do I run a program with command-line parameters?

### ISSUE THREAD

**Issue by amber8706** [bbjimmy/YAB#13]
I tried to use "Launch", but it apparently doesn't allow passing command line parameters. 

P.S. I can't register on the forum http://yab.orgfree.com/forum. the verification email doesn't arrive. (ignore it if you can't influence it.)

**Comment by bbjimmy** [comment]
yab.orgfree.com/forum does not send emails. New  accounts are
activated after a manual review. Your accouynt is active.

On 12/15/20, amber8706 <notifications@github.com> wrote:
> I tried to use "Launch", but it apparently doesn't allow passing command
> line parameters.
>
> P.S. I can't register on the forum http://yab.orgfree.com/forum. the
> verification email doesn't arrive. (ignore it if you can't influence it.)
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bbjimmy/YAB/issues/13


-- 
bbjimmy

http://www.coquillemartialarts.com
http://www.fatelk.com
http://yab.orgfree.com
